apiVersion: v1
kind: ConfigMap
metadata:
  name: music-player-config
  namespace: music-player
data:
  config.json: |
    {
      "host": "0.0.0.0",
      "port": 3000,
      "music_directory": "songs",
      "max_queue_size": 50,
      "max_history_size": 10,
      "read_timeout": 15,
      "write_timeout": 15,
      "keep_alive_max_count": 20,
      "base_url": "",
      "log_format": "json"
    }
