#!/usr/bin/env bash
# Regenerates the Ansible inventories from Terraform outputs, so no IP is ever
# hand-edited. Run after `terraform apply` in terraform/aws and terraform/jenkins.
#
#   ./scripts/gen-inventory.sh
#
# Produces three inventories under ansible/ (all marked GENERATED):
#   inventory-ec2.ini           app, public IP   — for running playbooks from your machine
#   inventory-ec2-internal.ini  app, private IP  — for the Jenkins pipeline (in-VPC deploy)
#   inventory-jenkins.ini       jenkins, public IP
set -euo pipefail

cd "$(dirname "$0")/.."
AWS_DIR=terraform/aws
JENKINS_DIR=terraform/jenkins

app_public=$(terraform -chdir="$AWS_DIR" output -raw public_ip)
app_private=$(terraform -chdir="$AWS_DIR" output -raw private_ip)
jenkins_public=$(terraform -chdir="$JENKINS_DIR" output -raw jenkins_ip)

common="ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'"
gen_note="# GENERATED by scripts/gen-inventory.sh from Terraform outputs — do not hand-edit.
# Key auth via ssh-agent (run 'ssh-add' on your machine; Jenkins uses its own credential)."

cat > ansible/inventory-ec2.ini <<EOF
$gen_note
# App instance, reached over its public IP (for running playbooks from your machine).

[ec2_host]
music-player-ec2 ansible_host=${app_public} ${common}
EOF

cat > ansible/inventory-ec2-internal.ini <<EOF
$gen_note
# App instance, reached over its PRIVATE IP — used by the Jenkins pipeline, which
# runs inside the VPC and deploys over the private network (no public round-trip).

[ec2_host]
music-player-ec2 ansible_host=${app_private} ${common}
EOF

cat > ansible/inventory-jenkins.ini <<EOF
$gen_note
# Jenkins / monitoring instance, reached over its public IP.

[jenkins_host]
music-player-jenkins ansible_host=${jenkins_public} ${common}
EOF

echo "Wrote ansible/inventory-ec2.ini (app $app_public)"
echo "Wrote ansible/inventory-ec2-internal.ini (app $app_private)"
echo "Wrote ansible/inventory-jenkins.ini (jenkins $jenkins_public)"
